/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/onboarding-screens` | `/onboarding-screens`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/storage` | `/storage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | { pathname: `/api/axios`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/onboarding-screens` | `/onboarding-screens`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/storage` | `/storage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownOutputParams; } | { pathname: `/api/axios`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/onboarding-screens${`?${string}` | `#${string}` | ''}` | `/onboarding-screens${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/storage${`?${string}` | `#${string}` | ''}` | `/storage${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/bookmarks${`?${string}` | `#${string}` | ''}` | `/bookmarks${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/tickets${`?${string}` | `#${string}` | ''}` | `/tickets${`?${string}` | `#${string}` | ''}` | `/api/axios${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/onboarding-screens` | `/onboarding-screens`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/storage` | `/storage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | { pathname: `/api/axios`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
